//nolint:staticcheck // zz_generated_deepcopy.go contains DeepCopy methods for all CRD types.
// In production, this file would be generated by controller-gen (code generation).
// We implement it manually here to avoid the controller-gen toolchain dependency.
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// ensure metav1 is used
var _ = metav1.Condition{}

// ─── AppleGPUCluster ─────────────────────────────────────────────────────────

func (in *AppleGPUCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *AppleGPUCluster) DeepCopy() *AppleGPUCluster {
	if in == nil {
		return nil
	}
	out := new(AppleGPUCluster)
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return out
}

func (in *AppleGPUClusterSpec) DeepCopyInto(out *AppleGPUClusterSpec) {
	*out = *in
	if in.NodeSelector != nil {
		out.NodeSelector = make(map[string]string, len(in.NodeSelector))
		for k, v := range in.NodeSelector {
			out.NodeSelector[k] = v
		}
	}
}

func (in *AppleGPUClusterStatus) DeepCopyInto(out *AppleGPUClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		copy(out.Conditions, in.Conditions)
	}
}

// ─── AppleGPUClusterList ─────────────────────────────────────────────────────

func (in *AppleGPUClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *AppleGPUClusterList) DeepCopy() *AppleGPUClusterList {
	if in == nil {
		return nil
	}
	out := new(AppleGPUClusterList)
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]AppleGPUCluster, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
	return out
}

func (in *AppleGPUCluster) DeepCopyInto(out *AppleGPUCluster) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// ─── MetalWorkload ────────────────────────────────────────────────────────────

func (in *MetalWorkload) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *MetalWorkload) DeepCopy() *MetalWorkload {
	if in == nil {
		return nil
	}
	out := new(MetalWorkload)
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return out
}

func (in *MetalWorkload) DeepCopyInto(out *MetalWorkload) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *MetalWorkloadSpec) DeepCopyInto(out *MetalWorkloadSpec) {
	*out = *in
	if in.PodSelector != nil {
		out.PodSelector = make(map[string]string, len(in.PodSelector))
		for k, v := range in.PodSelector {
			out.PodSelector[k] = v
		}
	}
}

func (in *MetalWorkloadStatus) DeepCopyInto(out *MetalWorkloadStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		copy(out.Conditions, in.Conditions)
	}
	if in.ActiveJobIDs != nil {
		out.ActiveJobIDs = make([]string, len(in.ActiveJobIDs))
		copy(out.ActiveJobIDs, in.ActiveJobIDs)
	}
}

// ─── MetalWorkloadList ────────────────────────────────────────────────────────

func (in *MetalWorkloadList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *MetalWorkloadList) DeepCopy() *MetalWorkloadList {
	if in == nil {
		return nil
	}
	out := new(MetalWorkloadList)
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]MetalWorkload, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
	return out
}

// (No type alias needed - metav1.Condition is used directly)
