// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/metal.proto

package metalpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Backend int32

const (
	Backend_BACKEND_UNSPECIFIED   Backend = 0
	Backend_BACKEND_MLX           Backend = 1 // Apple MLX framework
	Backend_BACKEND_PYTORCH_MPS   Backend = 2 // PyTorch Metal Performance Shaders backend
	Backend_BACKEND_METAL_COMPUTE Backend = 3 // Raw Metal Compute shaders (kernel path)
)

// Enum value maps for Backend.
var (
	Backend_name = map[int32]string{
		0: "BACKEND_UNSPECIFIED",
		1: "BACKEND_MLX",
		2: "BACKEND_PYTORCH_MPS",
		3: "BACKEND_METAL_COMPUTE",
	}
	Backend_value = map[string]int32{
		"BACKEND_UNSPECIFIED":   0,
		"BACKEND_MLX":           1,
		"BACKEND_PYTORCH_MPS":   2,
		"BACKEND_METAL_COMPUTE": 3,
	}
)

func (x Backend) Enum() *Backend {
	p := new(Backend)
	*p = x
	return p
}

func (x Backend) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Backend) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_metal_proto_enumTypes[0].Descriptor()
}

func (Backend) Type() protoreflect.EnumType {
	return &file_proto_metal_proto_enumTypes[0]
}

func (x Backend) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Backend.Descriptor instead.
func (Backend) EnumDescriptor() ([]byte, []int) {
	return file_proto_metal_proto_rawDescGZIP(), []int{0}
}

type Priority int32

const (
	Priority_PRIORITY_NORMAL Priority = 0
	Priority_PRIORITY_HIGH   Priority = 1
	Priority_PRIORITY_BATCH  Priority = 2 // lowest priority, best-effort
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_NORMAL",
		1: "PRIORITY_HIGH",
		2: "PRIORITY_BATCH",
	}
	Priority_value = map[string]int32{
		"PRIORITY_NORMAL": 0,
		"PRIORITY_HIGH":   1,
		"PRIORITY_BATCH":  2,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_metal_proto_enumTypes[1].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_proto_metal_proto_enumTypes[1]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_proto_metal_proto_rawDescGZIP(), []int{1}
}

type JobState int32

const (
	JobState_STATE_QUEUED    JobState = 0
	JobState_STATE_RUNNING   JobState = 1
	JobState_STATE_SUCCEEDED JobState = 2
	JobState_STATE_FAILED    JobState = 3
	JobState_STATE_CANCELLED JobState = 4
	JobState_STATE_THROTTLED JobState = 5 // paused due to thermal throttling
)

// Enum value maps for JobState.
var (
	JobState_name = map[int32]string{
		0: "STATE_QUEUED",
		1: "STATE_RUNNING",
		2: "STATE_SUCCEEDED",
		3: "STATE_FAILED",
		4: "STATE_CANCELLED",
		5: "STATE_THROTTLED",
	}
	JobState_value = map[string]int32{
		"STATE_QUEUED":    0,
		"STATE_RUNNING":   1,
		"STATE_SUCCEEDED": 2,
		"STATE_FAILED":    3,
		"STATE_CANCELLED": 4,
		"STATE_THROTTLED": 5,
	}
)

func (x JobState) Enum() *JobState {
	p := new(JobState)
	*p = x
	return p
}

func (x JobState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_metal_proto_enumTypes[2].Descriptor()
}

func (JobState) Type() protoreflect.EnumType {
	return &file_proto_metal_proto_enumTypes[2]
}

func (x JobState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobState.Descriptor instead.
func (JobState) EnumDescriptor() ([]byte, []int) {
	return file_proto_metal_proto_rawDescGZIP(), []int{2}
}

type ThermalState int32

const (
	ThermalState_THERMAL_NOMINAL  ThermalState = 0
	ThermalState_THERMAL_FAIR     ThermalState = 1
	ThermalState_THERMAL_SERIOUS  ThermalState = 2
	ThermalState_THERMAL_CRITICAL ThermalState = 3
)

// Enum value maps for ThermalState.
var (
	ThermalState_name = map[int32]string{
		0: "THERMAL_NOMINAL",
		1: "THERMAL_FAIR",
		2: "THERMAL_SERIOUS",
		3: "THERMAL_CRITICAL",
	}
	ThermalState_value = map[string]int32{
		"THERMAL_NOMINAL":  0,
		"THERMAL_FAIR":     1,
		"THERMAL_SERIOUS":  2,
		"THERMAL_CRITICAL": 3,
	}
)

func (x ThermalState) Enum() *ThermalState {
	p := new(ThermalState)
	*p = x
	return p
}

func (x ThermalState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThermalState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_metal_proto_enumTypes[3].Descriptor()
}

func (ThermalState) Type() protoreflect.EnumType {
	return &file_proto_metal_proto_enumTypes[3]
}

func (x ThermalState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ThermalState.Descriptor instead.
func (ThermalState) EnumDescriptor() ([]byte, []int) {
	return file_proto_metal_proto_rawDescGZIP(), []int{3}
}

// ─────────────────────────────────────────────────────────────────────────────
// Empty message (used as no-argument placeholder)
// ─────────────────────────────────────────────────────────────────────────────
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_metal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_metal_proto_rawDescGZIP(), []int{0}
}

type JobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique caller-assigned ID; used for idempotent re-submission.
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Which compute backend to use.
	Backend Backend `protobuf:"varint,2,opt,name=backend,proto3,enum=metal.Backend" json:"backend,omitempty"`
	// Scheduling priority.
	Priority Priority `protobuf:"varint,3,opt,name=priority,proto3,enum=metal.Priority" json:"priority,omitempty"`
	// Serialised payload — interpretation depends on backend:
	//
	//	MLX: JSON-encoded model path + input tensor shapes
	//	PYTORCH_MPS: serialised TorchScript model + inputs
	//	METAL_COMPUTE: compiled .metallib bytes + kernel name + args
	Payload []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	// Maximum wall-clock seconds before the proxy forcibly terminates the job.
	TimeoutSeconds uint32 `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	// Caller-supplied metadata (e.g. pod name, namespace, trace-id).
	Labels        map[string]string `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobRequest) Reset() {
	*x = JobRequest{}
	mi := &file_proto_metal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRequest) ProtoMessage() {}

func (x *JobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRequest.ProtoReflect.Descriptor instead.
func (*JobRequest) Descriptor() ([]byte, []int) {
	return file_proto_metal_proto_rawDescGZIP(), []int{1}
}

func (x *JobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobRequest) GetBackend() Backend {
	if x != nil {
		return x.Backend
	}
	return Backend_BACKEND_UNSPECIFIED
}

func (x *JobRequest) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_NORMAL
}

func (x *JobRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *JobRequest) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *JobRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type JobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"` // false if queue is full / job rejected
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`      // human-readable rejection reason
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResponse) Reset() {
	*x = JobResponse{}
	mi := &file_proto_metal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResponse) ProtoMessage() {}

func (x *JobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResponse.ProtoReflect.Descriptor instead.
func (*JobResponse) Descriptor() ([]byte, []int) {
	return file_proto_metal_proto_rawDescGZIP(), []int{2}
}

func (x *JobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *JobResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_metal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_metal_proto_rawDescGZIP(), []int{3}
}

func (x *StatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State         JobState               `protobuf:"varint,2,opt,name=state,proto3,enum=metal.JobState" json:"state,omitempty"`
	QueuePosition uint32                 `protobuf:"varint,3,opt,name=queue_position,json=queuePosition,proto3" json:"queue_position,omitempty"` // 0 when running
	ProgressPct   float32                `protobuf:"fixed32,4,opt,name=progress_pct,json=progressPct,proto3" json:"progress_pct,omitempty"`      // 0–100, hint only
	Result        []byte                 `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`                                     // set on SUCCEEDED; serialised output tensor(s)
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`     // set on FAILED
	GpuTimeUs     uint64                 `protobuf:"varint,7,opt,name=gpu_time_us,json=gpuTimeUs,proto3" json:"gpu_time_us,omitempty"`           // metal command-buffer GPU execution time
	WallTimeUs    uint64                 `protobuf:"varint,8,opt,name=wall_time_us,json=wallTimeUs,proto3" json:"wall_time_us,omitempty"`        // total elapsed wall time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatus) Reset() {
	*x = JobStatus{}
	mi := &file_proto_metal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatus) ProtoMessage() {}

func (x *JobStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatus.ProtoReflect.Descriptor instead.
func (*JobStatus) Descriptor() ([]byte, []int) {
	return file_proto_metal_proto_rawDescGZIP(), []int{4}
}

func (x *JobStatus) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobStatus) GetState() JobState {
	if x != nil {
		return x.State
	}
	return JobState_STATE_QUEUED
}

func (x *JobStatus) GetQueuePosition() uint32 {
	if x != nil {
		return x.QueuePosition
	}
	return 0
}

func (x *JobStatus) GetProgressPct() float32 {
	if x != nil {
		return x.ProgressPct
	}
	return 0
}

func (x *JobStatus) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *JobStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *JobStatus) GetGpuTimeUs() uint64 {
	if x != nil {
		return x.GpuTimeUs
	}
	return 0
}

func (x *JobStatus) GetWallTimeUs() uint64 {
	if x != nil {
		return x.WallTimeUs
	}
	return 0
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_proto_metal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_proto_metal_proto_rawDescGZIP(), []int{5}
}

func (x *CancelRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cancelled     bool                   `protobuf:"varint,1,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_proto_metal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_proto_metal_proto_rawDescGZIP(), []int{6}
}

func (x *CancelResponse) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

func (x *CancelResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeviceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// e.g. "Apple M3 Max"
	ChipName string `protobuf:"bytes,1,opt,name=chip_name,json=chipName,proto3" json:"chip_name,omitempty"`
	// e.g. "m3-max"
	ChipVariant string `protobuf:"bytes,2,opt,name=chip_variant,json=chipVariant,proto3" json:"chip_variant,omitempty"`
	// GPU core count as reported by Metal (MTLDevice.maximumConcurrentCompilationTaskCount
	// is not the right API; we use IOKit / system_profiler).
	GpuCores uint32 `protobuf:"varint,3,opt,name=gpu_cores,json=gpuCores,proto3" json:"gpu_cores,omitempty"`
	// Apple Neural Engine TOPS rating.
	AneTops float32 `protobuf:"fixed32,4,opt,name=ane_tops,json=aneTops,proto3" json:"ane_tops,omitempty"`
	// Unified memory shared between CPU and GPU, in bytes.
	UnifiedMemoryBytes uint64 `protobuf:"varint,5,opt,name=unified_memory_bytes,json=unifiedMemoryBytes,proto3" json:"unified_memory_bytes,omitempty"`
	// Metal GPU family (e.g. "apple9").
	GpuFamily string `protobuf:"bytes,6,opt,name=gpu_family,json=gpuFamily,proto3" json:"gpu_family,omitempty"`
	// Supported backends on this node.
	SupportedBackends []Backend `protobuf:"varint,7,rep,packed,name=supported_backends,json=supportedBackends,proto3,enum=metal.Backend" json:"supported_backends,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_proto_metal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_proto_metal_proto_rawDescGZIP(), []int{7}
}

func (x *DeviceInfo) GetChipName() string {
	if x != nil {
		return x.ChipName
	}
	return ""
}

func (x *DeviceInfo) GetChipVariant() string {
	if x != nil {
		return x.ChipVariant
	}
	return ""
}

func (x *DeviceInfo) GetGpuCores() uint32 {
	if x != nil {
		return x.GpuCores
	}
	return 0
}

func (x *DeviceInfo) GetAneTops() float32 {
	if x != nil {
		return x.AneTops
	}
	return 0
}

func (x *DeviceInfo) GetUnifiedMemoryBytes() uint64 {
	if x != nil {
		return x.UnifiedMemoryBytes
	}
	return 0
}

func (x *DeviceInfo) GetGpuFamily() string {
	if x != nil {
		return x.GpuFamily
	}
	return ""
}

func (x *DeviceInfo) GetSupportedBackends() []Backend {
	if x != nil {
		return x.SupportedBackends
	}
	return nil
}

type HealthStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Healthy        bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	ThermalState   ThermalState           `protobuf:"varint,2,opt,name=thermal_state,json=thermalState,proto3,enum=metal.ThermalState" json:"thermal_state,omitempty"`
	GpuUtilPct     float32                `protobuf:"fixed32,3,opt,name=gpu_util_pct,json=gpuUtilPct,proto3" json:"gpu_util_pct,omitempty"` // 0–100
	AneUtilPct     float32                `protobuf:"fixed32,4,opt,name=ane_util_pct,json=aneUtilPct,proto3" json:"ane_util_pct,omitempty"` // 0–100
	GpuPowerWatts  float32                `protobuf:"fixed32,5,opt,name=gpu_power_watts,json=gpuPowerWatts,proto3" json:"gpu_power_watts,omitempty"`
	JobsQueued     uint32                 `protobuf:"varint,6,opt,name=jobs_queued,json=jobsQueued,proto3" json:"jobs_queued,omitempty"`
	JobsRunning    uint32                 `protobuf:"varint,7,opt,name=jobs_running,json=jobsRunning,proto3" json:"jobs_running,omitempty"`
	SlotsTotal     uint32                 `protobuf:"varint,8,opt,name=slots_total,json=slotsTotal,proto3" json:"slots_total,omitempty"`
	SlotsAllocated uint32                 `protobuf:"varint,9,opt,name=slots_allocated,json=slotsAllocated,proto3" json:"slots_allocated,omitempty"`
	ProxyVersion   string                 `protobuf:"bytes,10,opt,name=proxy_version,json=proxyVersion,proto3" json:"proxy_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthStatus) Reset() {
	*x = HealthStatus{}
	mi := &file_proto_metal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatus) ProtoMessage() {}

func (x *HealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatus.ProtoReflect.Descriptor instead.
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return file_proto_metal_proto_rawDescGZIP(), []int{8}
}

func (x *HealthStatus) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthStatus) GetThermalState() ThermalState {
	if x != nil {
		return x.ThermalState
	}
	return ThermalState_THERMAL_NOMINAL
}

func (x *HealthStatus) GetGpuUtilPct() float32 {
	if x != nil {
		return x.GpuUtilPct
	}
	return 0
}

func (x *HealthStatus) GetAneUtilPct() float32 {
	if x != nil {
		return x.AneUtilPct
	}
	return 0
}

func (x *HealthStatus) GetGpuPowerWatts() float32 {
	if x != nil {
		return x.GpuPowerWatts
	}
	return 0
}

func (x *HealthStatus) GetJobsQueued() uint32 {
	if x != nil {
		return x.JobsQueued
	}
	return 0
}

func (x *HealthStatus) GetJobsRunning() uint32 {
	if x != nil {
		return x.JobsRunning
	}
	return 0
}

func (x *HealthStatus) GetSlotsTotal() uint32 {
	if x != nil {
		return x.SlotsTotal
	}
	return 0
}

func (x *HealthStatus) GetSlotsAllocated() uint32 {
	if x != nil {
		return x.SlotsAllocated
	}
	return 0
}

func (x *HealthStatus) GetProxyVersion() string {
	if x != nil {
		return x.ProxyVersion
	}
	return ""
}

var File_proto_metal_proto protoreflect.FileDescriptor

const file_proto_metal_proto_rawDesc = "" +
	"\n" +
	"\x11proto/metal.proto\x12\x05metal\"\a\n" +
	"\x05Empty\"\xaf\x02\n" +
	"\n" +
	"JobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12(\n" +
	"\abackend\x18\x02 \x01(\x0e2\x0e.metal.BackendR\abackend\x12+\n" +
	"\bpriority\x18\x03 \x01(\x0e2\x0f.metal.PriorityR\bpriority\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\rR\x0etimeoutSeconds\x125\n" +
	"\x06labels\x18\x06 \x03(\v2\x1d.metal.JobRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"X\n" +
	"\vJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"&\n" +
	"\rStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x92\x02\n" +
	"\tJobStatus\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12%\n" +
	"\x05state\x18\x02 \x01(\x0e2\x0f.metal.JobStateR\x05state\x12%\n" +
	"\x0equeue_position\x18\x03 \x01(\rR\rqueuePosition\x12!\n" +
	"\fprogress_pct\x18\x04 \x01(\x02R\vprogressPct\x12\x16\n" +
	"\x06result\x18\x05 \x01(\fR\x06result\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12\x1e\n" +
	"\vgpu_time_us\x18\a \x01(\x04R\tgpuTimeUs\x12 \n" +
	"\fwall_time_us\x18\b \x01(\x04R\n" +
	"wallTimeUs\"&\n" +
	"\rCancelRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"F\n" +
	"\x0eCancelResponse\x12\x1c\n" +
	"\tcancelled\x18\x01 \x01(\bR\tcancelled\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x94\x02\n" +
	"\n" +
	"DeviceInfo\x12\x1b\n" +
	"\tchip_name\x18\x01 \x01(\tR\bchipName\x12!\n" +
	"\fchip_variant\x18\x02 \x01(\tR\vchipVariant\x12\x1b\n" +
	"\tgpu_cores\x18\x03 \x01(\rR\bgpuCores\x12\x19\n" +
	"\bane_tops\x18\x04 \x01(\x02R\aaneTops\x120\n" +
	"\x14unified_memory_bytes\x18\x05 \x01(\x04R\x12unifiedMemoryBytes\x12\x1d\n" +
	"\n" +
	"gpu_family\x18\x06 \x01(\tR\tgpuFamily\x12=\n" +
	"\x12supported_backends\x18\a \x03(\x0e2\x0e.metal.BackendR\x11supportedBackends\"\x81\x03\n" +
	"\fHealthStatus\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x128\n" +
	"\rthermal_state\x18\x02 \x01(\x0e2\x13.metal.ThermalStateR\fthermalState\x12 \n" +
	"\fgpu_util_pct\x18\x03 \x01(\x02R\n" +
	"gpuUtilPct\x12 \n" +
	"\fane_util_pct\x18\x04 \x01(\x02R\n" +
	"aneUtilPct\x12&\n" +
	"\x0fgpu_power_watts\x18\x05 \x01(\x02R\rgpuPowerWatts\x12\x1f\n" +
	"\vjobs_queued\x18\x06 \x01(\rR\n" +
	"jobsQueued\x12!\n" +
	"\fjobs_running\x18\a \x01(\rR\vjobsRunning\x12\x1f\n" +
	"\vslots_total\x18\b \x01(\rR\n" +
	"slotsTotal\x12'\n" +
	"\x0fslots_allocated\x18\t \x01(\rR\x0eslotsAllocated\x12#\n" +
	"\rproxy_version\x18\n" +
	" \x01(\tR\fproxyVersion*g\n" +
	"\aBackend\x12\x17\n" +
	"\x13BACKEND_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vBACKEND_MLX\x10\x01\x12\x17\n" +
	"\x13BACKEND_PYTORCH_MPS\x10\x02\x12\x19\n" +
	"\x15BACKEND_METAL_COMPUTE\x10\x03*F\n" +
	"\bPriority\x12\x13\n" +
	"\x0fPRIORITY_NORMAL\x10\x00\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x01\x12\x12\n" +
	"\x0ePRIORITY_BATCH\x10\x02*\x80\x01\n" +
	"\bJobState\x12\x10\n" +
	"\fSTATE_QUEUED\x10\x00\x12\x11\n" +
	"\rSTATE_RUNNING\x10\x01\x12\x13\n" +
	"\x0fSTATE_SUCCEEDED\x10\x02\x12\x10\n" +
	"\fSTATE_FAILED\x10\x03\x12\x13\n" +
	"\x0fSTATE_CANCELLED\x10\x04\x12\x13\n" +
	"\x0fSTATE_THROTTLED\x10\x05*`\n" +
	"\fThermalState\x12\x13\n" +
	"\x0fTHERMAL_NOMINAL\x10\x00\x12\x10\n" +
	"\fTHERMAL_FAIR\x10\x01\x12\x13\n" +
	"\x0fTHERMAL_SERIOUS\x10\x02\x12\x14\n" +
	"\x10THERMAL_CRITICAL\x10\x032\x9f\x02\n" +
	"\x13MetalComputeService\x122\n" +
	"\tSubmitJob\x12\x11.metal.JobRequest\x1a\x12.metal.JobResponse\x12;\n" +
	"\x0fStreamJobStatus\x12\x14.metal.StatusRequest\x1a\x10.metal.JobStatus0\x01\x128\n" +
	"\tCancelJob\x12\x14.metal.CancelRequest\x1a\x15.metal.CancelResponse\x120\n" +
	"\rGetDeviceInfo\x12\f.metal.Empty\x1a\x11.metal.DeviceInfo\x12+\n" +
	"\x06Health\x12\f.metal.Empty\x1a\x13.metal.HealthStatusBBZ@github.com/gpu-operator-mac/apple-gpu-operator/pkg/proto;metalpbb\x06proto3"

var (
	file_proto_metal_proto_rawDescOnce sync.Once
	file_proto_metal_proto_rawDescData []byte
)

func file_proto_metal_proto_rawDescGZIP() []byte {
	file_proto_metal_proto_rawDescOnce.Do(func() {
		file_proto_metal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_metal_proto_rawDesc), len(file_proto_metal_proto_rawDesc)))
	})
	return file_proto_metal_proto_rawDescData
}

var file_proto_metal_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_metal_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_metal_proto_goTypes = []any{
	(Backend)(0),           // 0: metal.Backend
	(Priority)(0),          // 1: metal.Priority
	(JobState)(0),          // 2: metal.JobState
	(ThermalState)(0),      // 3: metal.ThermalState
	(*Empty)(nil),          // 4: metal.Empty
	(*JobRequest)(nil),     // 5: metal.JobRequest
	(*JobResponse)(nil),    // 6: metal.JobResponse
	(*StatusRequest)(nil),  // 7: metal.StatusRequest
	(*JobStatus)(nil),      // 8: metal.JobStatus
	(*CancelRequest)(nil),  // 9: metal.CancelRequest
	(*CancelResponse)(nil), // 10: metal.CancelResponse
	(*DeviceInfo)(nil),     // 11: metal.DeviceInfo
	(*HealthStatus)(nil),   // 12: metal.HealthStatus
	nil,                    // 13: metal.JobRequest.LabelsEntry
}
var file_proto_metal_proto_depIdxs = []int32{
	0,  // 0: metal.JobRequest.backend:type_name -> metal.Backend
	1,  // 1: metal.JobRequest.priority:type_name -> metal.Priority
	13, // 2: metal.JobRequest.labels:type_name -> metal.JobRequest.LabelsEntry
	2,  // 3: metal.JobStatus.state:type_name -> metal.JobState
	0,  // 4: metal.DeviceInfo.supported_backends:type_name -> metal.Backend
	3,  // 5: metal.HealthStatus.thermal_state:type_name -> metal.ThermalState
	5,  // 6: metal.MetalComputeService.SubmitJob:input_type -> metal.JobRequest
	7,  // 7: metal.MetalComputeService.StreamJobStatus:input_type -> metal.StatusRequest
	9,  // 8: metal.MetalComputeService.CancelJob:input_type -> metal.CancelRequest
	4,  // 9: metal.MetalComputeService.GetDeviceInfo:input_type -> metal.Empty
	4,  // 10: metal.MetalComputeService.Health:input_type -> metal.Empty
	6,  // 11: metal.MetalComputeService.SubmitJob:output_type -> metal.JobResponse
	8,  // 12: metal.MetalComputeService.StreamJobStatus:output_type -> metal.JobStatus
	10, // 13: metal.MetalComputeService.CancelJob:output_type -> metal.CancelResponse
	11, // 14: metal.MetalComputeService.GetDeviceInfo:output_type -> metal.DeviceInfo
	12, // 15: metal.MetalComputeService.Health:output_type -> metal.HealthStatus
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_metal_proto_init() }
func file_proto_metal_proto_init() {
	if File_proto_metal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_metal_proto_rawDesc), len(file_proto_metal_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_metal_proto_goTypes,
		DependencyIndexes: file_proto_metal_proto_depIdxs,
		EnumInfos:         file_proto_metal_proto_enumTypes,
		MessageInfos:      file_proto_metal_proto_msgTypes,
	}.Build()
	File_proto_metal_proto = out.File
	file_proto_metal_proto_goTypes = nil
	file_proto_metal_proto_depIdxs = nil
}
