// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/metal.proto

package metalpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetalComputeService_SubmitJob_FullMethodName       = "/metal.MetalComputeService/SubmitJob"
	MetalComputeService_StreamJobStatus_FullMethodName = "/metal.MetalComputeService/StreamJobStatus"
	MetalComputeService_CancelJob_FullMethodName       = "/metal.MetalComputeService/CancelJob"
	MetalComputeService_GetDeviceInfo_FullMethodName   = "/metal.MetalComputeService/GetDeviceInfo"
	MetalComputeService_Health_FullMethodName          = "/metal.MetalComputeService/Health"
)

// MetalComputeServiceClient is the client API for MetalComputeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetalComputeServiceClient interface {
	// SubmitJob enqueues a GPU/ANE compute job.
	SubmitJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobResponse, error)
	// StreamJobStatus streams status updates until the job reaches a terminal state.
	StreamJobStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobStatus], error)
	// CancelJob attempts to cancel a queued or running job.
	CancelJob(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error)
	// GetDeviceInfo returns static information about the Metal device on this node.
	GetDeviceInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DeviceInfo, error)
	// Health returns current health and utilization of the Metal proxy.
	Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthStatus, error)
}

type metalComputeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetalComputeServiceClient(cc grpc.ClientConnInterface) MetalComputeServiceClient {
	return &metalComputeServiceClient{cc}
}

func (c *metalComputeServiceClient) SubmitJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobResponse)
	err := c.cc.Invoke(ctx, MetalComputeService_SubmitJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metalComputeServiceClient) StreamJobStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MetalComputeService_ServiceDesc.Streams[0], MetalComputeService_StreamJobStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StatusRequest, JobStatus]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetalComputeService_StreamJobStatusClient = grpc.ServerStreamingClient[JobStatus]

func (c *metalComputeServiceClient) CancelJob(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelResponse)
	err := c.cc.Invoke(ctx, MetalComputeService_CancelJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metalComputeServiceClient) GetDeviceInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DeviceInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceInfo)
	err := c.cc.Invoke(ctx, MetalComputeService_GetDeviceInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metalComputeServiceClient) Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthStatus)
	err := c.cc.Invoke(ctx, MetalComputeService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetalComputeServiceServer is the server API for MetalComputeService service.
// All implementations must embed UnimplementedMetalComputeServiceServer
// for forward compatibility.
type MetalComputeServiceServer interface {
	// SubmitJob enqueues a GPU/ANE compute job.
	SubmitJob(context.Context, *JobRequest) (*JobResponse, error)
	// StreamJobStatus streams status updates until the job reaches a terminal state.
	StreamJobStatus(*StatusRequest, grpc.ServerStreamingServer[JobStatus]) error
	// CancelJob attempts to cancel a queued or running job.
	CancelJob(context.Context, *CancelRequest) (*CancelResponse, error)
	// GetDeviceInfo returns static information about the Metal device on this node.
	GetDeviceInfo(context.Context, *Empty) (*DeviceInfo, error)
	// Health returns current health and utilization of the Metal proxy.
	Health(context.Context, *Empty) (*HealthStatus, error)
	mustEmbedUnimplementedMetalComputeServiceServer()
}

// UnimplementedMetalComputeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetalComputeServiceServer struct{}

func (UnimplementedMetalComputeServiceServer) SubmitJob(context.Context, *JobRequest) (*JobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitJob not implemented")
}
func (UnimplementedMetalComputeServiceServer) StreamJobStatus(*StatusRequest, grpc.ServerStreamingServer[JobStatus]) error {
	return status.Error(codes.Unimplemented, "method StreamJobStatus not implemented")
}
func (UnimplementedMetalComputeServiceServer) CancelJob(context.Context, *CancelRequest) (*CancelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelJob not implemented")
}
func (UnimplementedMetalComputeServiceServer) GetDeviceInfo(context.Context, *Empty) (*DeviceInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeviceInfo not implemented")
}
func (UnimplementedMetalComputeServiceServer) Health(context.Context, *Empty) (*HealthStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedMetalComputeServiceServer) mustEmbedUnimplementedMetalComputeServiceServer() {}
func (UnimplementedMetalComputeServiceServer) testEmbeddedByValue()                             {}

// UnsafeMetalComputeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetalComputeServiceServer will
// result in compilation errors.
type UnsafeMetalComputeServiceServer interface {
	mustEmbedUnimplementedMetalComputeServiceServer()
}

func RegisterMetalComputeServiceServer(s grpc.ServiceRegistrar, srv MetalComputeServiceServer) {
	// If the following call panics, it indicates UnimplementedMetalComputeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetalComputeService_ServiceDesc, srv)
}

func _MetalComputeService_SubmitJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetalComputeServiceServer).SubmitJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetalComputeService_SubmitJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetalComputeServiceServer).SubmitJob(ctx, req.(*JobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetalComputeService_StreamJobStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MetalComputeServiceServer).StreamJobStatus(m, &grpc.GenericServerStream[StatusRequest, JobStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetalComputeService_StreamJobStatusServer = grpc.ServerStreamingServer[JobStatus]

func _MetalComputeService_CancelJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetalComputeServiceServer).CancelJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetalComputeService_CancelJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetalComputeServiceServer).CancelJob(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetalComputeService_GetDeviceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetalComputeServiceServer).GetDeviceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetalComputeService_GetDeviceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetalComputeServiceServer).GetDeviceInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetalComputeService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetalComputeServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetalComputeService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetalComputeServiceServer).Health(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// MetalComputeService_ServiceDesc is the grpc.ServiceDesc for MetalComputeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetalComputeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metal.MetalComputeService",
	HandlerType: (*MetalComputeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitJob",
			Handler:    _MetalComputeService_SubmitJob_Handler,
		},
		{
			MethodName: "CancelJob",
			Handler:    _MetalComputeService_CancelJob_Handler,
		},
		{
			MethodName: "GetDeviceInfo",
			Handler:    _MetalComputeService_GetDeviceInfo_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _MetalComputeService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamJobStatus",
			Handler:       _MetalComputeService_StreamJobStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/metal.proto",
}
